a=int(input("Hãy nhập số nguyên: "))
b=int(input("Hãy nhập số nguyên: "))
c=int(input("Hãy nhập số nguyên: "))
d=int(input("Hãy nhập số nguyên; "))
e=int(input("Hãy nhập số nguyên: "))
print("Tổng: ",a+b+c+d+e)
print("Trung bình: ",(a+b+c+d+e)/5)